name: BlockDuplicator
main: ca.strendin.Bukkit.BlockDuplicator.BlockDuplicator
version: 0.4
website: http://forums.bukkit.org
authors:
  - Mark Strendin
description: Duplicates blocks
commands:
  clearinv:
    aliases: [ci]
    description: Clears your inventory
    usage: |
           /<command>
  more:
    aliases: [m]
    description: Gives you more of what you are holding
    usage: |
           /<command> [stacks]  
  pick:
    aliases: []
    description: Sets the data value of what you are holding in your hand
    usage: |
           /<command> [value]
  duplicator:
    aliases: [duper]
    description: Gives you the duplicator tool
    usage: |
           /<command> 
  paintbrush:
    aliases: [painter]
    description: Gives you the paintbrush tool
    usage: |
           /<command>
  datatool:
    aliases: []
    description: Gives you the data tool
    usage: |
           /<command>
  bdtools:
    aliases: [btd]
    description: Gives you the duplicator, data and paintbrush tools
    usage: |
           /<command>
  blockduplicator:
    aliases: [bdreload]
    description: Reloads the configuration file
    usage: |
           /<command>              